/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.inzori.stripe;


import static androidx.core.app.ActivityCompat.startActivityForResult;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;

import android.content.Intent;

import com.stripe.android.identity.*;

@Kroll.module(name="Stripe", id="com.inzori.stripe")
public class StripeModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "StripeModule";
	private String ephemeralKeySecret = "";
	private String verificationSessionId = "";
	private static IdentityVerificationSheet identityVerificationSheet;


	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	public StripeModule()
	{
		super();

	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.w(LCAT, "inside onAppCreate 1");
		// put module init code that needs to run when the application is created
	}

	// Methods
	@Kroll.method
	public void startVerification(KrollDict options)
	{
		Log.w(LCAT, "startVerification called");

		verificationSessionId = options.containsKey("verificationSessionId") ? (String) options.get("verificationSessionId") : "";
		ephemeralKeySecret = options.containsKey("ephemeralKeySecret") ? (String) options.get("ephemeralKeySecret") : "";
		KrollFunction onComplete = (KrollFunction) options.get("onComplete");

		Intent intent = new Intent(TiApplication.getInstance().getApplicationContext(), StripeActivity.class);
		intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
		intent.putExtra("verificationSessionId", verificationSessionId);
		intent.putExtra("ephemeralKeySecret", ephemeralKeySecret);

		TiApplication.getInstance().getApplicationContext().startActivity(intent);
		//startActivityForResult(TiApplication.getAppCurrentActivity(), intent, 1, null);

	}

}

